const PoemsList = [
"I dont know where hes stationed, be it Cork or in Killarney",
"Together wed go roamin oer the mountains of Kilkenny",
"And I swear hed treat me fairer than my darlin sportin Jenny",
"Theres some takes delight in the carriages and rollin",
"Some takes delight in the hurley or the bollin",
"But I takes delight in the juice of the barley",
"Courtin pretty maids in the mornin, o so early",
"Oh the summertime is coming",
"And the trees are sweetly blooming",
"And the wild mountain thyme",
"Grows around the blooming heather",
"Will ye go, Lassie go",
"And well all go together",
"To pluck wild mountain thyme",
"All around the blooming heather",
"I will build my love a tower",
"Near yon pure crystal fountain",
"And on it I will build",
"All the flowers of the mountain",
"If my true love she were gone",
"I would surely find another",
"Where wild mountain thyme",
"When you are old and grey and full of sleep",
"And nodding by the fire, take down this book",
"And slowly read, and dream of the soft look",
"Your eyes had once, and of their shadows deep",
"How many loved your moments of glad grace",
"And loved your beauty with love false or true",
"But one man loved the pilgrim soul in you",
"And loved the sorrows of your changing face",
"And bending down beside the glowing bars",
"Murmur, a little sadly, how Love fled",
"And paced upon the mountains overhead",
"And hid his face amid a crowd of stars",
"How do I love thee? Let me count the ways",
"I love thee to the depth and breadth and height",
"My soul can reach, when feeling out of sight",
"For the ends of being and ideal grace",
"I love thee to the level of every day's",
"Most quiet need, by sun and candle-light",
]

export default PoemsList